### ISSUE TITLE
Xeno abilities can bypass critdrag oxyloss damage

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#10584]
### Description

You get oxyloss damage from critdrag in order to stop xenos just braziling people. Problem is it may only happen when dragging, so some abilities like crusher's grapple toss and shrike's fling/UF can displace marines in crit for several screens bypassing the intent of the pr that added said oxyloss.

### Test Merges

[#10425: 'Adds Dispenser, take Â³' by SplinterGP at commit 3038f38f9a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10425)

### Reproduction Steps

Get punted in crit
Get crusher tossed or flung
Again
Again
Again
You're dead 2 screens away when normal drag would've killed you in less than half that amount

**Comment by 2whatever2** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/6273

Pr that added corpsedrag oxyloss

https://github.com/tgstation/TerraGov-Marine-Corps/pull/6693

Pr that made wraith blinkdrags do oxyloss, and makes shrike and warrior unable to displace dead.

**Comment by Wayland-Smithy** [comment]
The amount of whack-a-mole the body drag prevention has caused is surly beyond measure. With the minimap now existing I'd like to see what rounds without this arbitrary restriction would look like.

**Comment by Denthamos** [comment]
> The amount of whack-a-mole the body drag prevention has caused is surly beyond measure. With the minimap now existing I'd like to see what rounds without this arbitrary restriction would look like.

Just because you can see someone on the minimap does not mean you can reach them when a rouny decides to take them so far away that its practically impossible to reach them due to the horde of xenos in your way before their defib timer goes off. 

Would also mean xenos would pretty much only cocoon at that point for the extra psy points if you can drag someone off into the distance with no restrictions.
