### ISSUE TITLE
Funny autoclimb behavior

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#10720]
### Description

Not a bug but probably unintended/annoying behavior:
If you run around and bump into climbable objects as you're moving, you get 'stuck' for a short moment every time while climb activates, slowing you down.

If you try push a climbable, movable object (like a crate), if you cancel the autoclimb, the object gets moved (even if you moved away from it, for example).
Combining the two above, in addition to the above slowing you down, if you keep pushing into a crate, every step actually pushes the crate two tiles forwards.

Climbing window frames diagonally teleports you past the frame instead of on top of it. I didn't investigate this deeply, so it potentially occurs with other objects/other situations.

### Test Merges

#10715

### Reproduction Steps

Description.

**Comment by Losenis** [comment]
It's annoying yeah. From exhaustive and controlled testing that amounts to 3 seconds of random bored req cratepushing, specifically, the issue is that autoclimbing stops your movement on bumping a climbable object. On the next movement it actually lets you move.

For moving objects, it gets weirder. If you bump against a crate, first it attempts to climb but it also "stores" the memory that you pushed it. If you move, the crate will get pushed from the direction you moved to, even if you're not even pushing it. For example, let's say you're south of a crate and move into it. You'll start climbing it but not push it. If you then move to the left and cancel the climbing, the crate will get pushed _northeast_.

The autoclimbing also happens if you're inside a ripley. You'll actually get "kicked out" of the ripley as you're stuck in place on the autoclimb but the ripley keeps moving one tile, for example when you're diagonally moving past a table. You're still considered inside the ripley though, so when you move, the ripley will move, and you'll get rubberbanded inside.

**Comment by lbnesquik** [comment]
Autoclimb is dead, aint it?

**Comment by QualityVan** [comment]
Autoclimb is long dead, yeah.
