### ISSUE TITLE
Crusher can double the range of crest toss by using it diagonally

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/TerraGov-Marine-Corps#14265]
### Description

Crusher crest toss range is mathematically doubled by using it diagonally.
Crest toss has a range of 6? tiles. If you use it diagonally, the marine will travel the full 6 tiles diagonally. 
Both mathematically and displacement-wise, this is double the distance.

### Test Merges

N/A

### Reproduction Steps

1) Be crusher
2) Stand diagonal to a human (North west, north east, south east or south west corner)
3) Crest toss

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/6613514/0309b379-c55b-41b1-a659-1182f3935b31

https://github.com/tgstation/TerraGov-Marine-Corps/assets/6613514/4846bda8-c22f-4a11-9999-02b860093dad

**Comment by Lumipharon** [comment]
This is actually a funny one.
So this is not strictly speaking a bug. Whats happening is that cresttoss has a range of 6, but the code actually finds the target turf from the XENO'S turf, while the THROW is measured from the throwee's turf. So the throwee is actually thrown 5 tiles not 6, since they are moved behind the xeno first.

Throws then measure euclide distance to see if you've bypassed max range or not. Because the human isn't actually thrown the max distance away when throwing straight, the diagonal distance allows for the 'true' 6 tile range.

You'll note in your video the human is 6 tiles west of the crusher but only 5 tiles south.

**Comment by GrayRachnid** [comment]
From east to west, the starting and ending spots are the same.
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6613514/488fb4fc-05f3-40a6-90a3-ec271ed495b3)

If you count the tile the crusher is on, the human travels 7 tiles going west.
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6613514/ef1794c0-cff3-4067-88b6-b16324515d12)

In diagonal movement, they move 7 tiles west and 6 tiles south.

**Comment by Lumipharon** [comment]
did you actually read what I said?
the mob is thrown from the X. So the RANGE is set from the X.
The actual tile target is set from the CRUSHER. So its not thrown full range when thrown in a straight cardinal direction.
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/d28ec895-7ef8-4ebc-81ec-3471a530fe67)

**Comment by GrayRachnid** [comment]
Ah I see.

It's still a lot.
