### ISSUE TITLE
Ricochet death tile bug

### ISSUE THREAD

**Issue by HanderBoy** [tgstation/TerraGov-Marine-Corps#15535]
### Description

The ricochet creates duped projectiles when interacting with a solid wall and a obstructing object ex. doors, shutters, resin walls even that creates a stream of 28(I counted the hits multiple times) invisible ricochet projectiles that hit everything that comes in contact with that tile.
The bug is mainly happens because of the buggy behaviour the ricochet sniper rifle has with anything that it can hit and is NOT a wall aditionally if you hit it in the wall in front of you the beam will IGNORE you and pass through to ricochet anything else if the tile behind you also has no space between you it will phase through you AGAIN into an infinite loop until the rico dries of beams.

### Test Merges

Round ID 26381 

### Reproduction Steps

1.Put the las sniper on ricochet mode
2.Sandwich yourself between a wall tile and any sort of non ricocheable tile .shutter doors .normal doors .worked on resin walls once
3.Fire
4.You created a invisible death trap that has a 20% chance to kill you if you step out of it have fun!

https://github.com/tgstation/TerraGov-Marine-Corps/assets/76793032/333df996-8dfc-42ba-b4a5-997f23786306

### Screenshots

Send a video up in reproduction

**Comment by Notamaniac** [comment]
Okay so it triggers a max recursion exception, which irrc is stopping the laser from processing and causing it to hang about, but it technically isn't recursion. From trying to interpret the callstack, it doesn't properly see the door as a dense object, but bounces off it regardless and fires directly from the open turf hence why it doesn't hit us. The amount a shot can bounce around is determined by it's range, and that range var is going down by one everytime it bounces. It's just that the range var is 30, and that's the max level of recursion that can occur before the exception triggers.

So option A : Do a check for airlocks/doors/objects on scan_a_turf, instead of just checking the turfs density
option B : hard limit the number of bounces to a number that's below 30
option C : remove bounce completely

**Comment by HanderBoy** [comment]
> Okay so it triggers a max recursion exception, which irrc is stopping the laser from processing and causing it to hang about, but it technically isn't recursion. From trying to interpret the callstack, it doesn't properly see the door as a dense object, but bounces off it regardless and fires directly from the open turf hence why it doesn't hit us. The amount a shot can bounce around is determined by it's range, and that range var is going down by one everytime it bounces. It's just that the range var is 30, and that's the max level of recursion that can occur before the exception triggers.
> 
> So option A : Do a check for airlocks/doors/objects on scan_a_turf, instead of just checking the turfs density option B : hard limit the number of bounces to a number that's below 30 option C : remove bounce completely

Thanks for the documentation! Ok so changing the amount of bounces needed for it to dissipate in the reflect code fixes it if you put it at 2
When I tried fixing it myself my dumbass only set it to dissipate when it went to 1 bounce and bellow and turns out if I had put it at 2 and bellow It would've been fixed 😭

**Comment by coldironwarrior** [comment]
just wanted to say kudos to you figuring out the combo here; this bug has been for years

**Comment by Lumipharon** [comment]
Fixed, forgot to link
