### ISSUE TITLE
Pounce through water offset

### ISSUE THREAD

**Issue by ju45he** [tgstation/TerraGov-Marine-Corps#15865]
### Description

I was playing hunter one day on TGMC and I pounced and my sprite got offset upwards permenantly, did it a few more times and it stacked.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [26988](https://scrubby.melonmesa.com/round/26988)
BYOND Version: 515.1633
Server revision compiled on: 2024-05-14T18:52:38+00:00
Master commit: [6b197a65a4bade96ede91042db1adc2e7aeae68e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/6b197a65a4bade96ede91042db1adc2e7aeae68e)
The following pull requests are currently test merged:
[#15682: 'Smooth move update' by Lumipharon at commit 7782067652](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15682)
[#15647: 'Health analyzer update' by Neocloudy at commit b4d0ee7abe](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15647)
[#15783: 'Adds the CPC (Clone Personnel Carrier) module' by Lumipharon at commit bcabb5fabf](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15783)
[#15839: 'Ports Kutjevo Refinery' by RipGrayson at commit c6cf651025](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15839)

Local commit: 3f6792e65acb353fc9b0b6cdf9e58ebb72325ec5
Server tools version: 6.5.0

### Reproduction Steps

1. Go to some water
2. Play as some caste that has access to some sort of pounce like hunter
3. Pounce across the water, from land on one side to land on the other
4. Sprite is offset and can be stacked to unreasonable degree

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/98619455/e5cfa1ea-10d0-44bc-9c76-38d21da43e32)

**Comment by Lumipharon** [comment]
this is due to throws (which includes pounces) basically traveling faster than its expecting a mob to move.
When it goes onto a shore turf, it removes the filter, on a timer based on your move delay. When you leave the shore turf for dry land, it checks again to make sure it removes the filter, but during a throw, you move faster than your move delay would allow, so you do in fact still have that filter again. So it removes it again, including adjusting the pixel_y.

Ultimately this behavior probably needs to be on an SS instead of the turf itself.
