### ISSUE TITLE
Goats go joker mode even if they're dead

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#16420]
### Description

I got their goat

### Test Merges

![image](https://github.com/user-attachments/assets/32cf3557-01fc-4e63-938a-37621fc7e742)

### Reproduction Steps

1. Find goat corpse
2. hit it
3. goat wants revenge

### Screenshots

![image](https://github.com/user-attachments/assets/12d14f0e-7bef-4050-ab30-52c185c40143)

**Comment by mrhugo13** [comment]
This appears to be caused by this proc
![Code_2024-08-11_14-43-42](https://github.com/user-attachments/assets/3831b29b-143e-4013-8c94-adaf5938ef47)

Which triggers the Retaliate() proc when hostile/retaliate creature is hit (with brute damage, atleast) without checking if the animal is alive or not.

PRing fix now.
