### ISSUE TITLE
Most maps have holodeck related items placed in them

### ISSUE THREAD

**Issue by Jalleo** [tgstation/TerraGov-Marine-Corps#1668]
Related type paths are 

BigRed_v2.dmm  /obj/structure/table/holotable/wood and /obj/item/toy/beach_ball/holoball
Ice_Colony_v2.dmm  /obj/item/toy/beach_ball/holoball

LV624.dmm /obj/structure/holohoop

Prison_Station_FOP.dmm /obj/structure/holohoop , /obj/item/toy/beach_ball/holoball

TGS_Theseus.dmm /obj/item/toy/beach_ball/holoball , /obj/structure/holohoop

Why this is bad:
If someone decides to bring back the holodeck and get it working properly these items would automatically be affected and removed under their current pathing. Also they are under a different code path than they should be to make them maintainable.

**Comment by DominikPanic** [comment]
Not sure if exactly a bug but meh

**Comment by Rohesie** [comment]
Map kind of bug.

**Comment by Jalleo** [comment]
The holohoop is less a bug and more a we need to create a actual structure for this rather than leaving it in the old path.

**Comment by DominikPanic** [comment]
Bad design != bug

**Comment by Rohesie** [comment]
Former mappers did a lot of bad intentional design that's very against our own intentions.
This is an issue, as it blocks porting holo code, and it's simply the wrong path types.
The report highlights the need to change it. It is not a features request, it's merely pointing out a simple and concrete thing to fix. It's useful and not bloating the issue list.
