### ISSUE TITLE
Storage screen click rutime

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#2738]
## Testmerges:

Round ID: 873
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 9e86e70d53f470d192a2c32f8c379d5791984ea7
The following pull requests are currently test merged:
#2726: 'Improve the UI of the marine vendors' by psykzz at commit dc819f73d7
#2618: 'Wolvesnotbear' by psykzz at commit 4789840dff
#2647: 'Removes focus chat' by DominikPanic at commit eef3223efc
#2477: 'The Rise of the ST' by Maciekkub at commit d54db15f70
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit 3541fbd902
#2679: 'Balance patch - marine weapons nerf.' by Rohesie at commit d008a90fff
#2643: 'Pseudo-pixel projectiles' by Rohesie at commit bcc8504701

## Reproduction:

```
[20:56:26] Runtime in storage.dm, line 281: list index out of bounds
proc name: Click (/obj/screen/storage/Click)
usr: Alibouk/(Collin Edwards)
usr.loc: (Canterbury (76, 29, 2))
src: the storage (/obj/screen/storage)
src.loc: null
call stack:
the storage (/obj/screen/storage): Click(null, "mapwindow.map", "icon-x=27;icon-y=16;vis-x=152;...")
Alibouk (/client): Click(the storage (/obj/screen/storage), null, "mapwindow.map", "icon-x=27;icon-y=16;vis-x=152;...")
```

**Comment by DominikPanic** [comment]
Always ask the people and PM them as soon as it happens to find out what was fucky

**Comment by DominikPanic** [comment]
This is impossible to solve without asking the person in a PM, so the time to report this could have gotten us a cause already.

**Comment by Rohesie** [comment]
Re-opened as per discussed on discord.

**Comment by Alibouk1** [comment]
This bug had occured on the first round I played on yesterday's test, I had joined as a PFC and starting getting myself equipped when I tried to put a flarepack in my backpack, as a result the Gray box that usually shows the amount of space taken by an item appeared without the sprite and the sprite stayed in my hand, usually the sprite fixed itself if I pressed Q to drop the sprite that's out of its spot but this time it just disappeared and didn't appear in the backpack leaving a gray area filled with no way to remove it due to how clicking it doesn't remove the item but rather clicking the sprite. although later on in a confusing manner I noticed that when I started filling up the satchel, the gray space box seemed to have disappeared and left room for me to put other items in.
