### ISSUE TITLE
Fog is easily exploitable

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#2879]
Currently, xenos are able to bring either live or dead humans across the fog barrier. I have seen this most often used on LV. 

##Test merges: 
#2833: 'Removes MP skill and tank access from PMC' by Maciekkub at commit 40ac2c25dc
#2854: 'Changes the Integrated Storage to hold a gun.' by Hughgent at commit fb2887bfe8
#2853: '4 Helmet Storage Slots' by Aurelien3189 at commit b7d267ebaf
#2852: 'Small M39 Mags' by Aurelien3189 at commit ca3b2fd1fb
#2814: 'Interaction rework' by DominikPanic at commit 77f44adfe3
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051
#2870: 'Fixes adminwho without mentors' by DominikPanic at commit b3972144b9
#2869: 'Removed Queen screech's screen shake for xenomorphs' by GhostAvenger at commit 2e690ea617
#2871: 'Fixes flares not burning weeds' by DominikPanic at commit 3a1797b7be
#2873: 'Youtubedl tweaks' by DominikPanic at commit c7d3d30e29

## Reproduction:
Ways I have seen it done:
1. Xeno sits on the fog, devours, and moves across the Fog
2. I didn't directly see it but I believe a dead nested human was grabbed and dragged across the fog, I have not tested this yet.

**Comment by MiniMeatwad** [comment]
This is done using the mechanic that if you pull someone and click on a nest/chair it moves them to that nest/chair. 
Marines were being pulled to the fog, and since there was a nest inside of the fog it was possible to move the marine from one side to the other. 

Possible ways to fix this would be to: 
Make double thick walls of fog. 
Make it so nests can't be built near fog.
(Or... you could remove a perfectly fine feature, which is clicking to move people onto nests easily, so you don't have to drag them onto the nest and then put them in.)
