### ISSUE TITLE
Cannot use T to talk.

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#4694]
## Reproduction: 
A new player or anyone who has not rebind-ed the hotkey for using "Say" verb will not be able to talk, thus being mute until a staff member or otherwise tells them how to fix this issue.
Not a huge problem as it can be fixed in-game, but because of how often it happens it is noticeable.

**Comment by factoryman942** [comment]
if they're too weak to use the chatbar at the bottom they deserve to be silenced anyway

**Comment by Hathkar** [comment]
Yeah, this has been a very consistent issue almost every round.

**Comment by Chaznoodles** [comment]
We're dealing with multiple mhelps daily asking why they can't talk and if they've been muted - and those are just the ones that mhelp instead of leaving because they can't talk. I'm surprised that, despite it being such a common and well-known issue, it requires to be flagged on github for someone to notice it.
