### ISSUE TITLE
Invincible cade exploit

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#4791]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 5008
BYOND Version: 513.1528
Server revision compiled on: 
Master commit: a2486260dd64faa4af9a9ddafc3f9fdffb4fbc51
The following pull requests are currently test merged:
#4763: 'buffs GL firespeed, reduces movepeed' by RenGusta at commit fe59f15c1d
#4727: 'Buffs Incendiary OB fire into the same as X Fuel (Blue Fire)' by 2whatever2 at commit 20b88f3524
#4647: 'Headphones' by TiviPlus at commit 6301166081
#4740: 'PSG Auto Sniper' by David-Stormwell at commit e08e6dcad5
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8

Local commit: 107563d83717fb19e0ffb6002893edc9b507619e
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. Grab some metal and some rglass
2. Build a cade and barb wire it
3. Unwrench the cade and put it somewhere else
4. Then do a directional glass where you want the cade to be
5. Wrench the cade ontop of the directional glass
6. Attempt to hit the cade while standing infront of it (if you do multiple then you can try on the sides too)
7. Watch as you can't hit the cade cause the window is blocking both alt click and the cade sprite, making them invincible to normal slashes.

Notes: 
>It's important you do the glass first and then put in the cade, else it doesn't work
>Seems like it also allows people to shoot through the glass when they're ontop of the cade, making it even more OP

**Comment by henriquekill9576** [comment]
Apparently it only gets hidden on cades that are facing south, but it still allows people to shoot through it while protecting the other cades, that's still a pretty big thing imo

**Comment by Pariah919** [comment]
The cade isn't invincible to slashes, the glass is just over it. So break the glass? I don't generally see what's wrong with this outside of making spitters have to actually fight through it. The glass also makes marines unable to actually fire through the cade unless they're directly ontop and blocks flamer hits,grenades, huggers, etc, blocks rockets...
I don't see what's wrong with this outside of "oh nooo the marines traded razorwire and a lot of other things for minorly more hp on a cade. I can't believe this."
It's emergent. Adapt. I'd rather see this be an actual game mechanic since it actually offers something interesting as a tradeoff in FOBs. Just fix the south bug and it'll be fine, in my opinion.

**Comment by henriquekill9576** [comment]
Yes I made this issue report before finding out it just works when facing south, although I haven't closed it cause shooting through the windows doesn't seem really right for me and to also get the south bug fixed aswell

**Comment by davidchan13** [comment]
I can say from my observation it's not just south facing cades that this workson. East facing cades works as well, the only thing marines can't do is lob grenades over the glass, guns still work fine. I don't know that the glass makes the cade invincible but the 2 spitters in the round that game were having an exceptional amount of trouble given glass is supposed to shatter after 2 or 3 hits from acid spit.

**Comment by MiniMeatwad** [comment]
Just fix stacking reinforced glass, having 10 reinforced glass windows in the same spot is just silly
