### ISSUE TITLE
Powernet generates too early making it impossible to charge the ship without reloading it.

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#481]
As title states, with LaKiller we have discovered that while SMES are outputting power they don't reach the APCs at the start of the round which drains them while cables are flowing with energy.

**Comment by Menshin** [comment]
It's because the associated terminals don't have a powernet.
The power is code is really old (pre 2014 update), i'll update it to the current standard that solved the issue.

Bandaid fix for the players meanwhile : cut the node code connecting the terminal to the powergrid, then rebuild it. It should connect the terminal to the correct powernet.

**Comment by Menshin** [comment]
Fixed by #592 .
