### ISSUE TITLE
Examine shows the wrong icon.

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#494]
## Testmerges:

#123 #480 #482 #485 #474 #320 #453 #459 #464 #451 #367 #439 #440 #447 #465 #468 #469 #488 #479 #478 #457

## Reproduction:

![sleeps](https://user-images.githubusercontent.com/42041276/52160758-38bd5380-26a2-11e9-8c0b-746ae67c2833.png)

Examine shows the wrong icon.

**Comment by spookydonut** [comment]
ohhhhhhhh uh give me a few days to remember why this happens

**Comment by MrStonedOne** [comment]
I made /tg/'s current bicon, are we using that, or the ones that came with goonchat?

**Comment by DominikPanic** [comment]
I think we're using /vg/'s

**Comment by MrStonedOne** [comment]
Moving to /tg/'s bicon would be better, /vg/'s one also locks up the chat because the client has to decode a base64's icon string embedded in the html, and the same icon can be send repeatedly /tg/'s one uses passive sending and loading the assets up to the client's html temp folder so they can be embedded as normal web images

**Comment by DominikPanic** [comment]
Fixed in #659
