### ISSUE TITLE
Asset licencing 

### ISSUE THREAD

**Issue by drawsstuff** [tgstation/TerraGov-Marine-Corps#5000]
As it currently stands, TGMC lacks asset licencing documentation, unlike several other codebases. All of my current contributions to TGMC were made under CC BY-NC-SA 3.0, and clarification is going to be important going forward. It's possible for a codebase to have mixed license assets, but these need to be openly stated. I recommend creation of an asset license readme.txt that details and records which assets are under which domain. I only make this request because I have recently discovered /tg/ station operates under a CC BY-SA 3.0 unless otherwise stated, which is not what I licence my own works under. Making license clear is imperative.

**Comment by spookydonut** [comment]
@drawsstuff your tgmc contributions as it stands are under agpl 3 because no one ever specified a separate art license (which was dumb)

If you can clearly identify which are your contributions that are solely your unmodified work we can relicense those as CC BY NC SA 3.0 with a disclaimer in the repo.

We cant blanket relicense all the tgmc artistic work without contacting the artists and having them agree to it, and i know at least one of them is dead which means we'll always have some art licensed under agpl3

**Comment by drawsstuff** [comment]
You've already been blanket re licencing without realizing it. A majority of your current xenomorph sprites were made by fridge, for example, under CC BY-NC 3.0. By extension, my panther modification sprites also fall under CC BY-NC 3.0 because of this.
