### ISSUE TITLE
Acid spray from spitter or prae sometimes doesn't stun people if they walk into a already sprayed tile while it is activating.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#5859]
## Testmerges:
#5714: 'LV map update by shiryu' by SplinterGP at commit a5913da17c
#5457: 'Evasion Thwarted By Debuffs and Stagger/Slow Partial Refactor' by Surrealaser at commit d671494d16
#5662: 'Revert "auxtools debugger (#5530)"' by TiviPlus at commit e64a73edb2

**Comment by Drevenshek** [comment]
isn't it meant to stun people if you hit them with it

**Comment by MiniMeatwad** [comment]
It sometimes doesn't register as 'hitting' them if they're walking towards you when it's fired.

**Comment by SkeletalElite** [comment]
Stun affect happens when the acid spray "spreads" onto your tile. Sometimes can be timed (usually by luck) so that you move right in between the time it moves to your tile and the time it spread onto the tile you moved onto, meaning it treats it as if you just walked on a spray of acid.

Technically the same thing can happen with the GAU. 
Probably hard to reproduce in a private server due to a lack of time dilation.
