### ISSUE TITLE
Invisible Open Visor Helmet

### ISSUE THREAD

**Issue by Helphe** [tgstation/TerraGov-Marine-Corps#6075]
## Reproduction:

Take an open visor helmet from the vendor, apply paint onto it, but press cancel. You now have an invisible open visor helmet.
This also works with normal helmets, but not armor parts.

https://i.gyazo.com/fb35437da6b5c7603bc43cf8f28758db.png

**Comment by fernandos13** [comment]
i kinda like this

**Comment by ss13xDEED** [comment]
I did't mind it either, it was a nice aesthetic choice, but if berets and patrol hats have less armor value in exchange for aesthetics, no hat at all shouldn't give you full head armor. 

The annoying part is that once you wear it, you can't remove it yourself because there's no sprite to click on. You have to have someone else remove it from you.
