### ISSUE TITLE
Queen can't do overwatch using hive status, follow xeno tracker overrides Queen overwatch.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6349]
## Testmerges:
#6313 #6306 #5422 #6314 #6284 #6219

## Reproduction:
1. Press xeno name in hive status as queen.
2. It only tracks them.
3. Have to use the manual button for overwatch.

**Comment by Swagile** [comment]
yeah this is a huge issue; ive stopped watching xenos due to this

being able to quickly watch a xeno as a queen that yells "ONE MARINE HERE / SILO HUNTER / NEED HELP FLANK" is crucial and having to go through your list of abilities to find the camera button, then find their name in the list, really fucks shit up

**Comment by TiviPlus** [comment]
@BraveMole

**Comment by BraveMole** [comment]
Intended
