### ISSUE TITLE
Supply Beacon can be used as OB beacon

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#7724]
### Description

Supply beacons show up in Main Overwatch Console and can be used to fire Ob.

This not only is unintended but puts the massive risk of FF OB.

### Test Merges

Not required.

### Reproduction Steps

1. Put down supply beacon.
2. Use main overwatch console from cic.
3. Fire incen ob in fob and destroy all supplies.

**Comment by KornFlaks** [comment]
This is intentional, the code makes no distinction between OB and supply beacon.

https://github.com/BraveMole/TerraGov-Marine-Corps/blob/2f954d28e841bd73e413e58602760e04c89c3025/code/game/objects/machinery/squad_supply/supply_beacon.dm#L66

The req console supply drop instead pulls data from a different var, unique to supply beacons

https://github.com/BraveMole/TerraGov-Marine-Corps/blob/2f954d28e841bd73e413e58602760e04c89c3025/code/game/objects/machinery/squad_supply/supply_beacon.dm#L124
