### ISSUE TITLE
Instakill runner macro 2:20 AM moscow time

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#911]
## Testmerges:
https://ibb.co/KsxxXMw

**Comment by Monikawales** [comment]
4 actions in a single click

**Comment by DominikPanic** [comment]
What is the macro? We need more information to be able to identify and fix the issue.

**Comment by ma44** [comment]
Actually just message spam, the pounce normally doesn't do a slash, but does a slash with the savage ability triggered. Here's a nice explanation of all the lines
"pounces on" regular stun by the runner, doesn't deal damage
"savages" ability toggled when pouncing, this will do one attack_alien
"slashes" is the actual slice attack
"strikes with lethal speed!" gets displayed because it activated the hit and run bonus; this is **NOT** an additional attack

Overall its legit 1 attack with 4 lines of output
