### ISSUE TITLE
Taking an offered human makes you use your old skills, not the skills that human should have.

### ISSUE THREAD

**Issue by Nickkoranda** [tgstation/TerraGov-Marine-Corps#968]
Basically, if you're a squad medic or doctor and you become a tank crewmember, you'll have the medical skills from being a doctor instead of the skills of a tank crewmember.

**Comment by Kingtrin** [comment]
This is due to the skillset being linked to the mind instead of the body. Typically this was not something you would even see outside of admin intervention. This was an issue in #701 where newly created mobs via admin panels would have a null skillset. Nulling out the mind datum causes similar issues.

This issue ceases being a problem once a skillset is reassigned. When a mob is being offered the bare minimum should be to reassign the skillset based on the job of the mob in question, otherwise the game is going to assume it should use the skillset already present in the new mind.
