### ISSUE TITLE
Larval Huggers 80% of the time on direct hit wont activate !

### ISSUE THREAD

**Issue by vilereaver41** [tgstation/TerraGov-Marine-Corps#9836]
### Description

Title, tested in-game several times even on SSD people, on direct hit they wont activate.

### Test Merges

[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 361378815a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9738: 'Adds the TX-54 Grenade launcher' by Lumipharon at commit 1e72187e35](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9738)
[#9794: 'Make coverage code actually work' by Lumipharon at commit 4fc048292c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9794)

### Reproduction Steps

1 go carrier
2 find marine
3 throw larval hugger at marine via direct hit within range
4 it wont activate until internal timer turns on

**Comment by BraveMole** [comment]
Activate? What does that mean? And why do you think it should activate

**Comment by TiviPlus** [comment]
You need to clarify what activate means

**Comment by Arctrooper8** [comment]
I believe I have discovered the problem, and it is not exclusive to larva huggers.

https://user-images.githubusercontent.com/95723150/162548381-52a8e960-1c1e-414e-8564-3bc4aa4cb484.mp4

 If the carrier is closer than 2 tiles, such as being right next to or being one tile away, the hugger will seemingly not benefit from it's impact_time value (In facehuggers.dm) and will instead default to activate_time as if you had not made a direct hit. You can also notice how the hugger lands on top of the marine instead of landing beside them.

The third and fourth hugs show something else I notice, diagonal throws can be strange. The third hug is seemingly not hit by the hugger with it flying off the wall and landing near her, yet she takes impact damage and the hugger uses it's impact value.
And the fourth hug show that throwing diagonal does not count the diagonal tiles, but instead seems to calculate as if it were moving in a zig zag (I tested earlier and the max distance you can make an impact is with 4 tiles between you and your target). 

What this shows is that huggers will not impact marines at close range when throw (I'm not sure if this is intentional but my simple code dive shows nothing about distance).
And that diagonal throws calculate that distance differently when throw at direct angles (instead of counting four tiles, it seems to zig zag counting more than four).

On a side note, the carrier turret's does not "throw" it's huggers as they do not experience impact_time at all.

**Comment by Arctrooper8** [comment]
https://user-images.githubusercontent.com/95723150/162550595-0a8c5ccd-706a-4371-be13-85526bbb5bd0.mp4

Holy shit the quality, at least you can see the video now.
